const mongoose = require('mongoose');

const refundCounterSchema = new mongoose.Schema({
    _id: { type: String, required: true },
    seq: { type: Number, default: 0 },
});

const RefundCounter = mongoose.model('RefundCounter', refundCounterSchema);

const refundSchema = new mongoose.Schema(
    {
        refundId: {
            type: String,
            unique: true,
            // Don't mark as required since it's auto-generated by pre-save hook
        },
        order: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Order',
            required: true,
        },
        invoice: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Invoice',
            required: true,
        },
        customer: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Customer',
            required: true,
        },
        refundType: {
            type: String,
            enum: ['full', 'partial'],
            required: true,
        },
        totalRefundAmount: {
            type: Number,
            required: true,
            min: 0,
        },
        refundedItems: [{
            orderItemId: {
                type: mongoose.Schema.Types.ObjectId,
                required: true,
            },
            itemName: String,
            itemType: String,
            quantity: Number, // Add quantity field for refunded/damaged quantity
            refundAmount: Number,
            refundReason: {
                type: String,
                enum: ['Damaged', 'Lost', 'Delayed_Service', 'Quality_Issue', 'Customer_Complaint', 'Other'],
                required: true,
            },
            refundReasonDescription: String,
        }],
        fullOrderReason: {
            type: String,
            enum: ['Damaged', 'Lost', 'Delayed_Service', 'Quality_Issue', 'Customer_Complaint', 'Other'],
        },
        fullOrderReasonDescription: String,
        processedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        processedByName: String,
        ipAddress: String,
        status: {
            type: String,
            enum: ['pending', 'completed', 'failed'],
            default: 'completed',
        },
        notes: String,
    },
    { timestamps: true }
);

// Auto-generate Refund ID (REF-0001, REF-0002, ...)
refundSchema.pre('save', async function () {
    if (this.isNew && !this.refundId) {
        const counter = await RefundCounter.findByIdAndUpdate(
            'refundId',
            { $inc: { seq: 1 } },
            { new: true, upsert: true }
        );
        this.refundId = `REF-${String(counter.seq).padStart(4, '0')}`;
    }
});

// Ensure refundId is always set before validation
refundSchema.pre('validate', async function () {
    if (this.isNew && !this.refundId) {
        const counter = await RefundCounter.findByIdAndUpdate(
            'refundId',
            { $inc: { seq: 1 } },
            { new: true, upsert: true }
        );
        this.refundId = `REF-${String(counter.seq).padStart(4, '0')}`;
    }
});

module.exports = mongoose.model('Refund', refundSchema);
